### PR TITLE
Write cached images in binary format. Fixes #2.

### LINKED ISSUE #2: Cached image files should be written in binary format
Cached image files are opened with write permissions in text format, rather than in binary format (see https://github.com/linuxwhatelse/service.linuxwhatelse.notify/blob/6654aa3c1d3376e487f9a5d92dad412ce8fe2a88/addon/routes/notification.py#L57). As a consequence, saved PNG files are corrupt and cannot be displayed (at least when running Kodi in Windows).

### PR DESCRIPTION
**Pull request by abelgomez**
Change open mode form 'w' to 'wb'. See https://github.com/linuxwhatelse/service.linuxwhatelse.notify/issues/2.

### CODE REVIEW

**Comment by tadly** [comment]
Seems to still work on linux too.
Weird this would cause issues on windows but oh well.

Thanks for the fix :)

**Comment by abelgomez** [comment]
Well, it's normal since the first 8 bytes of a PNG file must be (in decimal) `137 80 78 71 13 10 26 10`. But `10` is the `LF` character (`\n`). Since new lines in Windows are `CR LF` (`13 10`, i.e. `\r\n`) rather than `LF` (`10`) only, when saving the file in text mode, the `LF`s (`10`) are converted to `CRLF`s (`13 10`). Thus, the first bytes are (incorrectly) saved as `137 80 78 71 13 13 10 26 13 10`. This conversion may also be applied in many other places 🙂

**Comment by tadly** [comment]
Yeah that makes sense.

This code is so freaking old and needs a complete makeover but I burnt out on this project so this has to do ':D

**Comment by abelgomez** [comment]
Anyway, works great. Thanks for your work.

**Pull request merged**
